# load data

In [7]:
import pandas as pd
import numpy as np
from copy import deepcopy
from sklearn import neighbors

In [2]:
alltrain=pd.read_csv("train.csv",index_col=0,header=0)
alltrain

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
alltest=pd.read_csv("test.csv",index_col=0,header=0)
alltest['SalePrice']=np.NaN
alltest

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,NaN
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,NaN
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,NaN
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,NaN
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [26]:
alldata=alltrain.append(alltest)
alldata

C:\Users\TEMP\ipykernel_17204\196925152.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  alldata=alltrain.append(alltest)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

# 法1：在原数据上用onehot替代

In [28]:
onehot2str={}
str_cols=["MSSubClass"]
for c in alldata.columns:
    # print(c,str(alldata[c].dtype))
    if str(alldata[c].dtype)=='object' or c in str_cols:
        str_cols.append(c)
        mapper={}
        mapper[0]=np.NaN
        idx=1
        for tag in alldata[c].unique():
            if pd.isna(tag):
                print("nan")
                continue
            mapper[idx]=tag
            alldata.loc[alldata[c].values==tag,c]=idx
            idx+=1

        onehot2str[c]=mapper
        alldata[c].fillna(0,inplace=True)
print(str_cols)
mapped_alldata=deepcopy(alldata)
alldata=alltrain.append(alltest)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
['MSSubClass', 'MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

C:\Users\TEMP\ipykernel_17204\2732536228.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  alldata=alltrain.append(alltest)

In [29]:
onehot2str

{'MSSubClass': {0: nan,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 13,
  14: 14,
  15: 15,
  16: 16},
 'MSZoning': {0: nan, 1: 'RL', 2: 'RM', 3: 'C (all)', 4: 'FV', 5: 'RH'},
 'Street': {0: nan, 1: 'Pave', 2: 'Grvl'},
 'Alley': {0: nan, 1: 'Grvl', 2: 'Pave'},
 'LotShape': {0: nan, 1: 'Reg', 2: 'IR1', 3: 'IR2', 4: 'IR3'},
 'LandContour': {0: nan, 1: 'Lvl', 2: 'Bnk', 3: 'Low', 4: 'HLS'},
 'Utilities': {0: nan, 1: 'AllPub', 2: 'NoSeWa'},
 'LotConfig': {0: nan,
  1: 'Inside',
  2: 'FR2',
  3: 'Corner',
  4: 'CulDSac',
  5: 'FR3'},
 'LandSlope': {0: nan, 1: 'Gtl', 2: 'Mod', 3: 'Sev'},
 'Neighborhood': {0: nan,
  1: 'CollgCr',
  2: 'Veenker',
  3: 'Crawfor',
  4: 'NoRidge',
  5: 'Mitchel',
  6: 'Somerst',
  7: 'NWAmes',
  8: 'OldTown',
  9: 'BrkSide',
  10: 'Sawyer',
  11: 'NridgHt',
  12: 'NAmes',
  13: 'SawyerW',
  14: 'IDOTRR',
  15: 'MeadowV',
  16: 'Edwards',
  17: 'Timber',
  18: 'Gilbert',
  19: 'StoneBr',
  20: 'ClearCr',
  21: 'NPkVill',
  22: 'Blmngtn',
  23: 'BrDale',
  24: 'SWISU',
  25: 'Blueste'},
 'Condition1': {0: nan,
  1: 'Norm',
  2: 'Feedr',
  3: 'PosN',
  4: 'Artery',
  5: 'RRAe',
  6: 'RRNn',
  7: 'RRAn',
  8: 'PosA',
  9: 'RRNe'},
 'Condition2': {0: nan,
  1: 'Norm',
  2: 'Artery',
  3: 'RRNn',
  4: 'Feedr',
  5: 'PosN',
  6: 'PosA',
  7: 'RRAn',
  8: 'RRAe'},
 'BldgType': {0: nan,
  1: '1Fam',
  2: '2fmCon',
  3: 'Duplex',
  4: 'TwnhsE',
  5: 'Twnhs'},
 'HouseStyle': {0: nan,
  1: '2Story',
  2: '1Story',
  3: '1.5Fin',
  4: '1.5Unf',
  5: 'SFoyer',
  6: 'SLvl',
  7: '2.5Unf',
  8: '2.5Fin'},
 'RoofStyle': {0: nan,
  1: 'Gable',
  2: 'Hip',
  3: 'Gambrel',
  4: 'Mansard',
  5: 'Flat',
  6: 'Shed'},
 'RoofMatl': {0: nan,
  1: 'CompShg',
  2: 'WdShngl',
  3: 'Metal',
  4: 'WdShake',
  5: 'Membran',
  6: 'Tar&Grv',
  7: 'Roll',
  8: 'ClyTile'},
 'Exterior1st': {0: nan,
  1: 'VinylSd',
  2: 'MetalSd',
  3: 'Wd Sdng',
  4: 'HdBoard',
  5: 'BrkFace',
  6: 'WdShing',
  7: 'CemntBd',
  8: 'Plywood',
  9: 'AsbShng',
  10: 'Stucco',
  11: 'BrkComm',
  12: 'AsphShn',
  13: 'Stone',
  14: 'ImStucc',
  15: 'CBlock'},
 'Exterior2nd': {0: nan,
  1: 'VinylSd',
  2: 'MetalSd',
  3: 'Wd Shng',
  4: 'HdBoard',
  5: 'Plywood',
  6: 'Wd Sdng',
  7: 'CmentBd',
  8: 'BrkFace',
  9: 'Stucco',
  10: 'AsbShng',
  11: 'Brk Cmn',
  12: 'ImStucc',
  13: 'AsphShn',
  14: 'Stone',
  15: 'Other',
  16: 'CBlock'},
 'MasVnrType': {0: nan, 1: 'BrkFace', 2: 'None', 3: 'Stone', 4: 'BrkCmn'},
 'ExterQual': {0: nan, 1: 'Gd', 2: 'TA', 3: 'Ex', 4: 'Fa'},
 'ExterCond': {0: nan, 1: 'TA', 2: 'Gd', 3: 'Fa', 4: 'Po', 5: 'Ex'},
 'Foundation': {0: nan,
  1: 'PConc',
  2: 'CBlock',
  3: 'BrkTil',
  4: 'Wood',
  5: 'Slab',
  6: 'Stone'},
 'BsmtQual': {0: nan, 1: 'Gd', 2: 'TA', 3: 'Ex', 4: 'Fa'},
 'BsmtCond': {0: nan, 1: 'TA', 2: 'Gd', 3: 'Fa', 4: 'Po'},
 'BsmtExposure': {0: nan, 1: 'No', 2: 'Gd', 3: 'Mn', 4: 'Av'},
 'BsmtFinType1': {0: nan,
  1: 'GLQ',
  2: 'ALQ',
  3: 'Unf',
  4: 'Rec',
  5: 'BLQ',
  6: 'LwQ'},
 'BsmtFinType2': {0: nan,
  1: 'Unf',
  2: 'BLQ',
  3: 'ALQ',
  4: 'Rec',
  5: 'LwQ',
  6: 'GLQ'},
 'Heating': {0: nan,
  1: 'GasA',
  2: 'GasW',
  3: 'Grav',
  4: 'Wall',
  5: 'OthW',
  6: 'Floor'},
 'HeatingQC': {0: nan, 1: 'Ex', 2: 'Gd', 3: 'TA', 4: 'Fa', 5: 'Po'},
 'CentralAir': {0: nan, 1: 'Y', 2: 'N'},
 'Electrical': {0: nan,
  1: 'SBrkr',
  2: 'FuseF',
  3: 'FuseA',
  4: 'FuseP',
  5: 'Mix'},
 'KitchenQual': {0: nan, 1: 'Gd', 2: 'TA', 3: 'Ex', 4: 'Fa'},
 'Functional': {0: nan,
  1: 'Typ',
  2: 'Min1',
  3: 'Maj1',
  4: 'Min2',
  5: 'Mod',
  6: 'Maj2',
  7: 'Sev'},
 'FireplaceQu': {0: nan, 1: 'TA', 2: 'Gd', 3: 'Fa', 4: 'Ex', 5: 'Po'},
 'GarageType': {0: nan,
  1: 'Attchd',
  2: 'Detchd',
  3: 'BuiltIn',
  4: 'CarPort',
  5: 'Basment',
  6: '2Types'},
 'GarageFinish': {0: nan, 1: 'RFn', 2: 'Unf', 3: 'Fin'},
 'GarageQual': {0: nan, 1: 'TA', 2: 'Fa', 3: 'Gd', 4: 'Ex', 5: 'Po'},
 'GarageCond': {0: nan, 1: 'TA', 2: 'Fa', 3: 'Gd', 4: 'Po', 5: 'Ex'},
 'PavedDrive': {0: nan, 1: 'Y', 2: 'N', 3: 'P'},
 'PoolQC': {0: nan, 1: 'Ex', 2: 'Fa', 3: 'Gd'},
 'Fence': {0: nan, 1: 'MnPrv', 2: 'GdWo', 3: 'GdPrv', 4: 'MnWw'},
 'MiscFeature': {0: nan, 1: 'Shed', 2: 'Gar2', 3: 'Othr', 4: 'TenC'},
 'SaleType': {0: nan,
  1: 'WD',
  2: 'New',
  3: 'COD',
  4: 'ConLD',
  5: 'ConLI',
  6: 'CWD',
  7: 'ConLw',
  8: 'Con',
  9: 'Oth'},
 'SaleCondition': {0: nan,
  1: 'Normal',
  2: 'Abnorml',
  3: 'Partial',
  4: 'AdjLand',
  5: 'Alloca',
  6: 'Family'}}

In [15]:
alldata

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

## fill in missing values - KNN

In [30]:
# 用于将上面map好的数据进行knn补全
tempdata=alldata.loc[:,~alldata.isna().any().values]
n_neighbors=10
# 如果包含空值的列是object列，那么是离散的，应该用聚类，否则回归
for col in alldata.columns[alldata.isnull().any().values]:
    if col=="SalePrice":
        continue
    # 按照行切分，提取非nan的行用于训练
    notnan=alldata.loc[:,col].notna()
    isnan=alldata.loc[:,col].isna()
    if col in str_cols:
        # 注意，这里选择用dummy来处理非数字的字段，而数字字段选择用knn来补全
        # 聚类
        clf = neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
        clf.fit(tempdata.loc[notnan], alldata.loc[notnan,col].astype(int))
        alldata.loc[isnan,col]=clf.predict(tempdata.loc[isnan])
    else:
        # 回归
        print(col)
        rgs = neighbors.KNeighborsRegressor(n_neighbors, weights='distance')
        rgs.fit(tempdata.loc[notnan], alldata.loc[notnan,col])
        alldata.loc[isnan,col]=rgs.predict(tempdata.loc[isnan])

LotFrontage
MasVnrArea
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
BsmtFullBath
BsmtHalfBath
GarageYrBlt
GarageCars
GarageArea

In [8]:
# dummy法：对数字nan进行补全
tempdata=mapped_alldata.loc[:,~mapped_alldata.isna().any().values]
n_neighbors=10
# 如果包含空值的列是object列，那么是离散的，应该用聚类，否则回归
for col in alldata.columns[alldata.isnull().any().values]:
    if col=="SalePrice":
        continue
    # 按照行切分，提取非nan的行用于训练
    notnan=alldata.loc[:,col].notna()
    isnan=alldata.loc[:,col].isna()
    if col not in str_cols:
        # 回归
        print(col)
        rgs = neighbors.KNeighborsRegressor(n_neighbors, weights='distance')
        rgs.fit(tempdata.loc[notnan], alldata.loc[notnan,col])
        alldata.loc[isnan,col]=rgs.predict(tempdata.loc[isnan])

LotFrontage
MasVnrArea
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
BsmtFullBath
BsmtHalfBath
GarageYrBlt
GarageCars
GarageArea

In [10]:
tempdata

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,8450,Pave,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,0,61,0,0,0,0,0,2,2008,Normal
2,20,9600,Pave,Reg,Lvl,FR2,Gtl,Veenker,Feedr,Norm,...,298,0,0,0,0,0,0,5,2007,Normal
3,60,11250,Pave,IR1,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,0,42,0,0,0,0,0,9,2008,Normal
4,70,9550,Pave,IR1,Lvl,Corner,Gtl,Crawfor,Norm,Norm,...,0,35,272,0,0,0,0,2,2006,Abnorml
5,60,14260,Pave,IR1,Lvl,FR2,Gtl,NoRidge,Norm,Norm,...,192,84,0,0,0,0,0,12,2008,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,1936,Pave,Reg,Lvl,Inside,Gtl,MeadowV,Norm,Norm,...,0,0,0,0,0,0,0,6,2006,Normal
2916,160,1894,Pave,Reg,Lvl,Inside,Gtl,MeadowV,Norm,Norm,...,0,24,0,0,0,0,0,4,2006,Abnorml
2917,20,20000,Pave,Reg,Lvl,Inside,Gtl,Mitchel,Norm,Norm,...,474,0,0,0,0,0,0,9,2006,Abnorml
2918,85,10441,Pave,Reg,Lvl,Inside,Gtl,Mitchel,Norm,Norm,...,80,32,0,0,0,0,700,7,2006,Normal
2919,60,9627,Pave,Reg,Lvl,Inside,Mod,Mitchel,Norm,Norm,...,190,48,0,0,0,0,0,11,2006,Normal

In [7]:
print(alldata.isna().any())
alldata.isna().any().value_counts()

MSSubClass       False
MSZoning          True
LotFrontage       True
LotArea          False
Street           False
                 ...
MoSold           False
YrSold           False
SaleType          True
SaleCondition    False
SalePrice         True
Length: 80, dtype: bool

False    45
True     35
dtype: int64

# 法2：新增dummy变量

将所有非数字的字段中的值视为虚拟变量（包括nan）

In [9]:
# dummy_na=True将缺失值也当作合法的特征值并为其创建指示特征
alldata_dummy = pd.get_dummies(alldata.iloc[:,:-1], dummy_na=True,drop_first=True,columns=str_cols)
alldata_dummy['SalePrice']=alldata.iloc[:,-1]
print(alldata_dummy.shape) # (2919, 320)
alldata_dummy

(2919, 320)

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,...,0,1,0,0,0,0,1,0,0,208500.0
2,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,...,0,1,0,0,0,0,1,0,0,181500.0
3,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,...,0,1,0,0,0,0,1,0,0,223500.0
4,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,540.0,...,0,1,0,0,0,0,0,0,0,140000.0
5,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,490.0,...,0,1,0,0,0,0,1,0,0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,546.0,...,0,1,0,0,0,0,1,0,0,NaN
2916,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,294.0,...,0,1,0,0,0,0,0,0,0,NaN
2917,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,NaN
2918,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,...,0,1,0,0,0,0,1,0,0,NaN
2919,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,...,0,1,0,0,0,0,1,0,0,NaN

In [10]:
alldata_dummy.to_csv("./alldata_dummy.csv")

In [11]:
alldata=deepcopy(alldata_dummy)

# split train and valid

In [12]:
test=alldata.loc[alldata.loc[:,"SalePrice"].isna()]
train1=alldata.loc[~alldata.loc[:,"SalePrice"].isna()]

In [13]:
sorted_train=train1.sort_values(["YrSold","MoSold"])
sorted_train

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
142,78.000000,11645,7,5,2005,2005,0.0,1300.0,0.0,434.0,...,0,1,0,0,0,0,1,0,0,260000.0
170,105.280550,16669,8,6,1981,1981,653.0,0.0,0.0,1686.0,...,0,1,0,0,0,0,1,0,0,228000.0
303,118.000000,13704,7,5,2001,2002,150.0,0.0,0.0,1541.0,...,0,1,0,0,0,0,1,0,0,205000.0
371,62.769282,8121,6,5,2000,2000,0.0,0.0,0.0,953.0,...,0,1,0,0,0,0,1,0,0,172400.0
412,100.000000,34650,5,5,1955,1955,0.0,1056.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,145000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,65.000000,8450,5,6,1968,1968,0.0,775.0,0.0,281.0,...,0,1,0,0,0,0,1,0,0,142000.0
706,70.000000,5600,4,5,1930,1950,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,55000.0
1145,60.000000,12180,4,4,1941,1950,0.0,348.0,0.0,324.0,...,0,1,0,0,0,0,1,0,0,80000.0
1161,24.000000,2280,6,5,1978,1978,0.0,311.0,0.0,544.0,...,0,1,0,0,0,0,1,0,0,146000.0
1422,53.000000,4043,6,5,1977,1977,0.0,360.0,0.0,709.0,...,0,1,0,0,0,0,1,0,0,127500.0

In [14]:
valid=sorted_train.groupby(["YrSold","MoSold"]).sample(frac=0.1, random_state=2)
valid

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
412,100.000000,34650,5,5,1955,1955,0.0,1056.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,145000.0
546,94.102105,13837,7,5,1988,1988,178.0,1002.0,202.0,0.0,...,0,1,0,0,0,0,1,0,0,229000.0
1247,65.000000,8125,7,5,2005,2006,0.0,0.0,0.0,756.0,...,0,0,0,0,0,0,0,1,0,186500.0
512,40.000000,6792,7,5,2005,2006,94.0,0.0,0.0,1368.0,...,0,0,0,0,0,0,0,1,0,202665.0
86,121.000000,16059,8,5,1991,1992,284.0,0.0,0.0,1288.0,...,0,1,0,0,0,0,1,0,0,260000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,60.559055,6820,8,5,1985,1985,0.0,368.0,1120.0,0.0,...,0,1,0,0,0,0,1,0,0,212000.0
143,71.000000,8520,5,4,1952,1952,0.0,507.0,0.0,403.0,...,0,1,0,0,0,0,1,0,0,166000.0
1381,45.000000,8212,3,3,1914,1950,0.0,203.0,0.0,661.0,...,0,1,0,0,0,0,1,0,0,58500.0
69,47.000000,4608,4,6,1945,1950,0.0,0.0,0.0,747.0,...,0,1,0,0,0,0,1,0,0,80000.0
706,70.000000,5600,4,5,1930,1950,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,1,0,0,55000.0

In [15]:
valid.groupby(["YrSold","MoSold"]).count()

               LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
YrSold MoSold
2006   1                 1        1            1            1          1
       2                 1        1            1            1          1
       3                 2        2            2            2          2
       4                 3        3            3            3          3
       5                 4        4            4            4          4
       6                 5        5            5            5          5
       7                 7        7            7            7          7
       8                 2        2            2            2          2
       9                 2        2            2            2          2
       10                2        2            2            2          2
       11                2        2            2            2          2
       12                1        1            1            1          1
2007   1                 1        1            1            1          1
       2                 1        1            1            1          1
       3                 2        2            2            2          2
       4                 2        2            2            2          2
       5                 4        4            4            4          4
       6                 6        6            6            6          6
       7                 5        5            5            5          5
       8                 4        4            4            4          4
       9                 1        1            1            1          1
       10                2        2            2            2          2
       11                2        2            2            2          2
       12                2        2            2            2          2
2008   1                 1        1            1            1          1
       2                 1        1            1            1          1
       3                 2        2            2            2          2
       4                 3        3            3            3          3
       5                 4        4            4            4          4
       6                 5        5            5            5          5
       7                 5        5            5            5          5
       8                 3        3            3            3          3
       9                 2        2            2            2          2
       10                2        2            2            2          2
       11                2        2            2            2          2
       12                1        1            1            1          1
2009   1                 1        1            1            1          1
       2                 1        1            1            1          1
       3                 2        2            2            2          2
       4                 3        3            3            3          3
       5                 4        4            4            4          4
       6                 6        6            6            6          6
       7                 6        6            6            6          6
       8                 3        3            3            3          3
       9                 2        2            2            2          2
       10                3        3            3            3          3
       11                2        2            2            2          2
       12                2        2            2            2          2
2010   1                 1        1            1            1          1
       2                 2        2            2            2          2
       3                 2        2            2            2          2
       4                 4        4            4            4          4
       5                 5        5            5            5          5
       6                 4        4            4            4          4
       7                 1        1            1            1          1

               YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  \
YrSold MoSold
2006   1                  1           1           1           1          1
       2                  1           1           1           1          1
       3                  2           2           2           2          2
       4                  3           3           3           3          3
       5                  4           4           4           4          4
       6                  5           5           5           5          5
       7                  7           7           7           7          7
       8                  2           2           2           2          2
       9                  2           2           2           2          2
       10                 2           2           2           2          2
       11                 2           2           2           2          2
       12                 1           1           1           1          1
2007   1                  1           1           1           1          1
       2                  1           1           1           1          1
       3                  2           2           2           2          2
       4                  2           2           2           2          2
       5                  4           4           4           4          4
       6                  6           6           6           6          6
       7                  5           5           5           5          5
       8                  4           4           4           4          4
       9                  1           1           1           1          1
       10                 2           2           2           2          2
       11                 2           2           2           2          2
       12                 2           2           2           2          2
2008   1                  1           1           1           1          1
       2                  1           1           1           1          1
       3                  2           2           2           2          2
       4                  3           3           3           3          3
       5                  4           4           4           4          4
       6                  5           5           5           5          5
       7                  5           5           5           5          5
       8                  3           3           3           3          3
       9                  2           2           2           2          2
       10                 2           2           2           2          2
       11                 2           2           2           2          2
       12                 1           1           1           1          1
2009   1                  1           1           1           1          1
       2                  1           1           1           1          1
       3                  2           2           2           2          2
       4                  3           3           3           3          3
       5                  4           4           4           4          4
       6                  6           6           6           6          6
       7                  6           6           6           6          6
       8                  3           3           3           3          3
       9                  2           2           2           2          2
       10                 3           3           3           3          3
       11                 2           2           2           2          2
       12                 2           2           2           2          2
2010   1                  1           1           1           1          1
       2                  2           2           2           2          2
       3                  2           2           2           2          2
       4                  4           4           4           4          4
       5                  5           5           5           5          5
       6                  4           4           4           4          4
       7                  1           1           1           1          1

               ...  SaleType_Oth  SaleType_WD  SaleType_nan  \
YrSold MoSold  ...
2006   1       ...             1            1             1
       2       ...             1            1             1
       3       ...             2            2             2
       4       ...             3            3             3
       5       ...             4            4             4
       6       ...             5            5             5
       7       ...             7            7             7
       8       ...             2            2             2
       9       ...             2            2             2
       10      ...             2            2             2
       11      ...             2            2             2
       12      ...             1            1             1
2007   1       ...             1            1             1
       2       ...             1            1             1
       3       ...             2            2             2
       4       ...             2            2             2
       5       ...             4            4             4
       6       ...             6            6             6
       7       ...             5            5             5
       8       ...             4            4             4
       9       ...             1            1             1
       10      ...             2            2             2
       11      ...             2            2             2
       12      ...             2            2             2
2008   1       ...             1            1             1
       2       ...             1            1             1
       3       ...             2            2             2
       4       ...             3            3             3
       5       ...             4            4             4
       6       ...             5            5             5
       7       ...             5            5             5
       8       ...             3            3             3
       9       ...             2            2             2
       10      ...             2            2             2
       11      ...             2            2             2
       12      ...             1            1             1
2009   1       ...             1            1             1
       2       ...             1            1             1
       3       ...             2            2             2
       4       ...             3            3             3
       5       ...             4            4             4
       6       ...             6            6             6
       7       ...             6            6             6
       8       ...             3            3             3
       9       ...             2            2             2
       10      ...             3            3             3
       11      ...             2            2             2
       12      ...             2            2             2
2010   1       ...             1            1             1
       2       ...             2            2             2
       3       ...             2            2             2
       4       ...             4            4             4
       5       ...             5            5             5
       6       ...             4            4             4
       7       ...             1            1             1

               SaleCondition_AdjLand  SaleCondition_Alloca  \
YrSold MoSold
2006   1                           1                     1
       2                           1                     1
       3                           2                     2
       4                           3                     3
       5                           4                     4
       6                           5                     5
       7                           7                     7
       8                           2                     2
       9                           2                     2
       10                          2                     2
       11                          2                     2
       12                          1                     1
2007   1                           1                     1
       2                           1                     1
       3                           2                     2
       4                           2                     2
       5                           4                     4
       6                           6                     6
       7                           5                     5
       8                           4                     4
       9                           1                     1
       10                          2                     2
       11                          2                     2
       12                          2                     2
2008   1                           1                     1
       2                           1                     1
       3                           2                     2
       4                           3                     3
       5                           4                     4
       6                           5                     5
       7                           5                     5
       8                           3                     3
       9                           2                     2
       10                          2                     2
       11                          2                     2
       12                          1                     1
2009   1                           1                     1
       2                           1                     1
       3                           2                     2
       4                           3                     3
       5                           4                     4
       6                           6                     6
       7                           6                     6
       8                           3                     3
       9                           2                     2
       10                          3                     3
       11                          2                     2
       12                          2                     2
2010   1                           1                     1
       2                           2                     2
       3                           2                     2
       4                           4                     4
       5                           5                     5
       6                           4                     4
       7                           1                     1

               SaleCondition_Family  SaleCondition_Normal  \
YrSold MoSold
2006   1                          1                     1
       2                          1                     1
       3                          2                     2
       4                          3                     3
       5                          4                     4
       6                          5                     5
       7                          7                     7
       8                          2                     2
       9                          2                     2
       10                         2                     2
       11                         2                     2
       12                         1                     1
2007   1                          1                     1
       2                          1                     1
       3                          2                     2
       4                          2                     2
       5                          4                     4
       6                          6                     6
       7                          5                     5
       8                          4                     4
       9                          1                     1
       10                         2                     2
       11                         2                     2
       12                         2                     2
2008   1                          1                     1
       2                          1                     1
       3                          2                     2
       4                          3                     3
       5                          4                     4
       6                          5                     5
       7                          5                     5
       8                          3                     3
       9                          2                     2
       10                         2                     2
       11                         2                     2
       12                         1                     1
2009   1                          1                     1
       2                          1                     1
       3                          2                     2
       4                          3                     3
       5                          4                     4
       6                          6                     6
       7                          6                     6
       8                          3                     3
       9                          2                     2
       10                         3                     3
       11                         2                     2
       12                         2                     2
2010   1                          1                     1
       2                          2                     2
       3                          2                     2
       4                          4                     4
       5                          5                     5
       6                          4                     4
       7                          1                     1

               SaleCondition_Partial  SaleCondition_nan  SalePrice
YrSold MoSold
2006   1                           1                  1          1
       2                           1                  1          1
       3                           2                  2          2
       4                           3                  3          3
       5                           4                  4          4
       6                           5                  5          5
       7                           7                  7          7
       8                           2                  2          2
       9                           2                  2          2
       10                          2                  2          2
       11                          2                  2          2
       12                          1                  1          1
2007   1                           1                  1          1
       2                           1                  1          1
       3                           2                  2          2
       4                           2                  2          2
       5                           4                  4          4
       6                           6                  6          6
       7                           5                  5          5
       8                           4                  4          4
       9                           1                  1          1
       10                          2                  2          2
       11                          2                  2          2
       12                          2                  2          2

In [16]:
sorted_train.groupby(["YrSold","MoSold"]).count()

               LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
YrSold MoSold
2006   1                10       10           10           10         10
       2                 9        9            9            9          9
       3                25       25           25           25         25
       4                27       27           27           27         27
       5                38       38           38           38         38
       6                48       48           48           48         48
       7                67       67           67           67         67
       8                23       23           23           23         23
       9                15       15           15           15         15
       10               24       24           24           24         24
       11               16       16           16           16         16
       12               12       12           12           12         12
2007   1                13       13           13           13         13
       2                 8        8            8            8          8
       3                23       23           23           23         23
       4                23       23           23           23         23
       5                43       43           43           43         43
       6                59       59           59           59         59
       7                51       51           51           51         51
       8                40       40           40           40         40
       9                11       11           11           11         11
       10               16       16           16           16         16
       11               24       24           24           24         24
       12               18       18           18           18         18
2008   1                13       13           13           13         13
       2                10       10           10           10         10
       3                18       18           18           18         18
       4                26       26           26           26         26
       5                38       38           38           38         38
       6                51       51           51           51         51
       7                49       49           49           49         49
       8                29       29           29           29         29
       9                17       17           17           17         17
       10               22       22           22           22         22
       11               17       17           17           17         17
       12               14       14           14           14         14
2009   1                12       12           12           12         12
       2                10       10           10           10         10
       3                19       19           19           19         19
       4                26       26           26           26         26
       5                37       37           37           37         37
       6                59       59           59           59         59
       7                61       61           61           61         61
       8                30       30           30           30         30
       9                20       20           20           20         20
       10               27       27           27           27         27
       11               22       22           22           22         22
       12               15       15           15           15         15
2010   1                10       10           10           10         10
       2                15       15           15           15         15
       3                21       21           21           21         21
       4                39       39           39           39         39
       5                48       48           48           48         48
       6                36       36           36           36         36
       7                 6        6            6            6          6

               YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  \
YrSold MoSold
2006   1                 10          10          10          10         10
       2                  9           9           9           9          9
       3                 25          25          25          25         25
       4                 27          27          27          27         27
       5                 38          38          38          38         38
       6                 48          48          48          48         48
       7                 67          67          67          67         67
       8                 23          23          23          23         23
       9                 15          15          15          15         15
       10                24          24          24          24         24
       11                16          16          16          16         16
       12                12          12          12          12         12
2007   1                 13          13          13          13         13
       2                  8           8           8           8          8
       3                 23          23          23          23         23
       4                 23          23          23          23         23
       5                 43          43          43          43         43
       6                 59          59          59          59         59
       7                 51          51          51          51         51
       8                 40          40          40          40         40
       9                 11          11          11          11         11
       10                16          16          16          16         16
       11                24          24          24          24         24
       12                18          18          18          18         18
2008   1                 13          13          13          13         13
       2                 10          10          10          10         10
       3                 18          18          18          18         18
       4                 26          26          26          26         26
       5                 38          38          38          38         38
       6                 51          51          51          51         51
       7                 49          49          49          49         49
       8                 29          29          29          29         29
       9                 17          17          17          17         17
       10                22          22          22          22         22
       11                17          17          17          17         17
       12                14          14          14          14         14
2009   1                 12          12          12          12         12
       2                 10          10          10          10         10
       3                 19          19          19          19         19
       4                 26          26          26          26         26
       5                 37          37          37          37         37
       6                 59          59          59          59         59
       7                 61          61          61          61         61
       8                 30          30          30          30         30
       9                 20          20          20          20         20
       10                27          27          27          27         27
       11                22          22          22          22         22
       12                15          15          15          15         15
2010   1                 10          10          10          10         10
       2                 15          15          15          15         15
       3                 21          21          21          21         21
       4                 39          39          39          39         39
       5                 48          48          48          48         48
       6                 36          36          36          36         36
       7                  6           6           6           6          6

               ...  SaleType_Oth  SaleType_WD  SaleType_nan  \
YrSold MoSold  ...
2006   1       ...            10           10            10
       2       ...             9            9             9
       3       ...            25           25            25
       4       ...            27           27            27
       5       ...            38           38            38
       6       ...            48           48            48
       7       ...            67           67            67
       8       ...            23           23            23
       9       ...            15           15            15
       10      ...            24           24            24
       11      ...            16           16            16
       12      ...            12           12            12
2007   1       ...            13           13            13
       2       ...             8            8             8
       3       ...            23           23            23
       4       ...            23           23            23
       5       ...            43           43            43
       6       ...            59           59            59
       7       ...            51           51            51
       8       ...            40           40            40
       9       ...            11           11            11
       10      ...            16           16            16
       11      ...            24           24            24
       12      ...            18           18            18
2008   1       ...            13           13            13
       2       ...            10           10            10
       3       ...            18           18            18
       4       ...            26           26            26
       5       ...            38           38            38
       6       ...            51           51            51
       7       ...            49           49            49
       8       ...            29           29            29
       9       ...            17           17            17
       10      ...            22           22            22
       11      ...            17           17            17
       12      ...            14           14            14
2009   1       ...            12           12            12
       2       ...            10           10            10
       3       ...            19           19            19
       4       ...            26           26            26
       5       ...            37           37            37
       6       ...            59           59            59
       7       ...            61           61            61
       8       ...            30           30            30
       9       ...            20           20            20
       10      ...            27           27            27
       11      ...            22           22            22
       12      ...            15           15            15
2010   1       ...            10           10            10
       2       ...            15           15            15
       3       ...            21           21            21
       4       ...            39           39            39
       5       ...            48           48            48
       6       ...            36           36            36
       7       ...             6            6             6

               SaleCondition_AdjLand  SaleCondition_Alloca  \
YrSold MoSold
2006   1                          10                    10
       2                           9                     9
       3                          25                    25
       4                          27                    27
       5                          38                    38
       6                          48                    48
       7                          67                    67
       8                          23                    23
       9                          15                    15
       10                         24                    24
       11                         16                    16
       12                         12                    12
2007   1                          13                    13
       2                           8                     8
       3                          23                    23
       4                          23                    23
       5                          43                    43
       6                          59                    59
       7                          51                    51
       8                          40                    40
       9                          11                    11
       10                         16                    16
       11                         24                    24
       12                         18                    18
2008   1                          13                    13
       2                          10                    10
       3                          18                    18
       4                          26                    26
       5                          38                    38
       6                          51                    51
       7                          49                    49
       8                          29                    29
       9                          17                    17
       10                         22                    22
       11                         17                    17
       12                         14                    14
2009   1                          12                    12
       2                          10                    10
       3                          19                    19
       4                          26                    26
       5                          37                    37
       6                          59                    59
       7                          61                    61
       8                          30                    30
       9                          20                    20
       10                         27                    27
       11                         22                    22
       12                         15                    15
2010   1                          10                    10
       2                          15                    15
       3                          21                    21
       4                          39                    39
       5                          48                    48
       6                          36                    36
       7                           6                     6

               SaleCondition_Family  SaleCondition_Normal  \
YrSold MoSold
2006   1                         10                    10
       2                          9                     9
       3                         25                    25
       4                         27                    27
       5                         38                    38
       6                         48                    48
       7                         67                    67
       8                         23                    23
       9                         15                    15
       10                        24                    24
       11                        16                    16
       12                        12                    12
2007   1                         13                    13
       2                          8                     8
       3                         23                    23
       4                         23                    23
       5                         43                    43
       6                         59                    59
       7                         51                    51
       8                         40                    40
       9                         11                    11
       10                        16                    16
       11                        24                    24
       12                        18                    18
2008   1                         13                    13
       2                         10                    10
       3                         18                    18
       4                         26                    26
       5                         38                    38
       6                         51                    51
       7                         49                    49
       8                         29                    29
       9                         17                    17
       10                        22                    22
       11                        17                    17
       12                        14                    14
2009   1                         12                    12
       2                         10                    10
       3                         19                    19
       4                         26                    26
       5                         37                    37
       6                         59                    59
       7                         61                    61
       8                         30                    30
       9                         20                    20
       10                        27                    27
       11                        22                    22
       12                        15                    15
2010   1                         10                    10
       2                         15                    15
       3                         21                    21
       4                         39                    39
       5                         48                    48
       6                         36                    36
       7                          6                     6

               SaleCondition_Partial  SaleCondition_nan  SalePrice
YrSold MoSold
2006   1                          10                 10         10
       2                           9                  9          9
       3                          25                 25         25
       4                          27                 27         27
       5                          38                 38         38
       6                          48                 48         48
       7                          67                 67         67
       8                          23                 23         23
       9                          15                 15         15
       10                         24                 24         24
       11                         16                 16         16
       12                         12                 12         12
2007   1                          13                 13         13
       2                           8                  8          8
       3                          23                 23         23
       4                          23                 23         23
       5                          43                 43         43
       6                          59                 59         59
       7                          51                 51         51
       8                          40                 40         40
       9                          11                 11         11
       10                         16                 16         16
       11                         24                 24         24
       12                         18                 18         18

In [17]:
train_idx=list(set(list(sorted_train.index)).difference(set(list(valid.index))))
len(train_idx)

1311

In [18]:
train=sorted_train.loc[train_idx].sort_values(by=["YrSold","MoSold"])
train

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
142,78.000000,11645,7,5,2005,2005,0.0,1300.0,0.0,434.0,...,0,1,0,0,0,0,1,0,0,260000.0
170,105.280550,16669,8,6,1981,1981,653.0,0.0,0.0,1686.0,...,0,1,0,0,0,0,1,0,0,228000.0
303,118.000000,13704,7,5,2001,2002,150.0,0.0,0.0,1541.0,...,0,1,0,0,0,0,1,0,0,205000.0
371,62.769282,8121,6,5,2000,2000,0.0,0.0,0.0,953.0,...,0,1,0,0,0,0,1,0,0,172400.0
665,49.000000,20896,8,5,2005,2006,0.0,1721.0,0.0,356.0,...,0,0,0,0,0,0,0,1,0,423000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,115.784974,19900,7,5,1970,1989,287.0,912.0,0.0,1035.0,...,0,1,0,0,0,0,1,0,0,180000.0
420,65.000000,8450,5,6,1968,1968,0.0,775.0,0.0,281.0,...,0,1,0,0,0,0,1,0,0,142000.0
1145,60.000000,12180,4,4,1941,1950,0.0,348.0,0.0,324.0,...,0,1,0,0,0,0,1,0,0,80000.0
1161,24.000000,2280,6,5,1978,1978,0.0,311.0,0.0,544.0,...,0,1,0,0,0,0,1,0,0,146000.0
1422,53.000000,4043,6,5,1977,1977,0.0,360.0,0.0,709.0,...,0,1,0,0,0,0,1,0,0,127500.0

In [19]:
set(list(train.index)).intersection(set(list(valid.index)))

set()

# save train

In [20]:
sorted_train.groupby(["YrSold","MoSold"]).mean().to_csv("mean_data.csv")

In [21]:
# train.to_csv("preprocessed_train.csv")
# valid.to_csv("preprocessed_valid.csv")
# test.to_csv("preprocessed_test.csv")

# dummy
train.to_csv("preprocessed_dummy_train.csv")
valid.to_csv("preprocessed_dummy_valid.csv")
test.to_csv("preprocessed_dummy_test.csv")

In [22]:
import json
with open("onehot2str.json","w") as f:
    json.dump(onehot2str,f)

TypeError: Object of type int64 is not JSON serializable

In [78]:
with open("onehot2str.json","r") as f:
    print(json.load(f))

{'MSZoning': {'1': 'RL', '2': 'RM', '3': 'C (all)', '4': 'FV', '5': 'RH', '6': nan}, 'Street': {'1': 'Pave', '2': 'Grvl'}, 'Alley': {'1': nan, '2': 'Grvl', '3': 'Pave'}, 'LotShape': {'1': 'Reg', '2': 'IR1', '3': 'IR2', '4': 'IR3'}, 'LandContour': {'1': 'Lvl', '2': 'Bnk', '3': 'Low', '4': 'HLS'}, 'Utilities': {'1': 'AllPub', '2': 'NoSeWa', '3': nan}, 'LotConfig': {'1': 'Inside', '2': 'FR2', '3': 'Corner', '4': 'CulDSac', '5': 'FR3'}, 'LandSlope': {'1': 'Gtl', '2': 'Mod', '3': 'Sev'}, 'Neighborhood': {'1': 'CollgCr', '2': 'Veenker', '3': 'Crawfor', '4': 'NoRidge', '5': 'Mitchel', '6': 'Somerst', '7': 'NWAmes', '8': 'OldTown', '9': 'BrkSide', '10': 'Sawyer', '11': 'NridgHt', '12': 'NAmes', '13': 'SawyerW', '14': 'IDOTRR', '15': 'MeadowV', '16': 'Edwards', '17': 'Timber', '18': 'Gilbert', '19': 'StoneBr', '20': 'ClearCr', '21': 'NPkVill', '22': 'Blmngtn', '23': 'BrDale', '24': 'SWISU', '25': 'Blueste'}, 'Condition1': {'1': 'Norm', '2': 'Feedr', '3': 'PosN', '4': 'Artery', '5': 'RRAe', '6': 'RRNn', '7': 'RRAn', '8': 'PosA', '9': 'RRNe'}, 'Condition2': {'1': 'Norm', '2': 'Artery', '3': 'RRNn', '4': 'Feedr', '5': 'PosN', '6': 'PosA', '7': 'RRAn', '8': 'RRAe'}, 'BldgType': {'1': '1Fam', '2': '2fmCon', '3': 'Duplex', '4': 'TwnhsE', '5': 'Twnhs'}, 'HouseStyle': {'1': '2Story', '2': '1Story', '3': '1.5Fin', '4': '1.5Unf', '5': 'SFoyer', '6': 'SLvl', '7': '2.5Unf', '8': '2.5Fin'}, 'RoofStyle': {'1': 'Gable', '2': 'Hip', '3': 'Gambrel', '4': 'Mansard', '5': 'Flat', '6': 'Shed'}, 'RoofMatl': {'1': 'CompShg', '2': 'WdShngl', '3': 'Metal', '4': 'WdShake', '5': 'Membran', '6': 'Tar&Grv', '7': 'Roll', '8': 'ClyTile'}, 'Exterior1st': {'1': 'VinylSd', '2': 'MetalSd', '3': 'Wd Sdng', '4': 'HdBoard', '5': 'BrkFace', '6': 'WdShing', '7': 'CemntBd', '8': 'Plywood', '9': 'AsbShng', '10': 'Stucco', '11': 'BrkComm', '12': 'AsphShn', '13': 'Stone', '14': 'ImStucc', '15': 'CBlock', '16': nan}, 'Exterior2nd': {'1': 'VinylSd', '2': 'MetalSd', '3': 'Wd Shng', '4': 'HdBoard', '5': 'Plywood', '6': 'Wd Sdng', '7': 'CmentBd', '8': 'BrkFace', '9': 'Stucco', '10': 'AsbShng', '11': 'Brk Cmn', '12': 'ImStucc', '13': 'AsphShn', '14': 'Stone', '15': 'Other', '16': 'CBlock', '17': nan}, 'MasVnrType': {'1': 'BrkFace', '2': 'None', '3': 'Stone', '4': 'BrkCmn', '5': nan}, 'ExterQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': 'Fa'}, 'ExterCond': {'1': 'TA', '2': 'Gd', '3': 'Fa', '4': 'Po', '5': 'Ex'}, 'Foundation': {'1': 'PConc', '2': 'CBlock', '3': 'BrkTil', '4': 'Wood', '5': 'Slab', '6': 'Stone'}, 'BsmtQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': nan, '5': 'Fa'}, 'BsmtCond': {'1': 'TA', '2': 'Gd', '3': nan, '4': 'Fa', '5': 'Po'}, 'BsmtExposure': {'1': 'No', '2': 'Gd', '3': 'Mn', '4': 'Av', '5': nan}, 'BsmtFinType1': {'1': 'GLQ', '2': 'ALQ', '3': 'Unf', '4': 'Rec', '5': 'BLQ', '6': nan, '7': 'LwQ'}, 'BsmtFinType2': {'1': 'Unf', '2': 'BLQ', '3': nan, '4': 'ALQ', '5': 'Rec', '6': 'LwQ', '7': 'GLQ'}, 'Heating': {'1': 'GasA', '2': 'GasW', '3': 'Grav', '4': 'Wall', '5': 'OthW', '6': 'Floor'}, 'HeatingQC': {'1': 'Ex', '2': 'Gd', '3': 'TA', '4': 'Fa', '5': 'Po'}, 'CentralAir': {'1': 'Y', '2': 'N'}, 'Electrical': {'1': 'SBrkr', '2': 'FuseF', '3': 'FuseA', '4': 'FuseP', '5': 'Mix', '6': nan}, 'KitchenQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': 'Fa', '5': nan}, 'Functional': {'1': 'Typ', '2': 'Min1', '3': 'Maj1', '4': 'Min2', '5': 'Mod', '6': 'Maj2', '7': 'Sev', '8': nan}, 'FireplaceQu': {'1': nan, '2': 'TA', '3': 'Gd', '4': 'Fa', '5': 'Ex', '6': 'Po'}, 'GarageType': {'1': 'Attchd', '2': 'Detchd', '3': 'BuiltIn', '4': 'CarPort', '5': nan, '6': 'Basment', '7': '2Types'}, 'GarageFinish': {'1': 'RFn', '2': 'Unf', '3': 'Fin', '4': nan}, 'GarageQual': {'1': 'TA', '2': 'Fa', '3': 'Gd', '4': nan, '5': 'Ex', '6': 'Po'}, 'GarageCond': {'1': 'TA', '2': 'Fa', '3': nan, '4': 'Gd', '5': 'Po', '6': 'Ex'}, 'PavedDrive': {'1': 'Y', '2': 'N', '3': 'P'}, 'PoolQC': {'1': nan, '2': 'Ex', '3': 'Fa', '4': 'Gd'}, 'Fence': {'1': nan, '2': 'MnPrv', '3': 'GdWo', '4': 'GdPrv', '5': 'MnWw'}, 'MiscFeature': {'1': nan, '2': 'Shed', '3': 'Gar2', '4': 'Othr', '5': 'TenC'}, 'SaleType': {'1': 'WD', '2': 'New', '3': 'COD', '4': 'ConLD', '5': 'ConLI', '6': 'CWD', '7': 'ConLw', '8': 'Con', '9': 'Oth', '10': nan}, 'SaleCondition': {'1': 'Normal', '2': 'Abnorml', '3': 'Partial', '4': 'AdjLand', '5': 'Alloca', '6': 'Family'}}