# load data

In [1]:
import pandas as pd
import numpy as np

In [2]:
alltrain=pd.read_csv("train.csv",index_col=0,header=0)
alltrain

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
alltest=pd.read_csv("test.csv",index_col=0,header=0)
alltest['SalePrice']=np.NaN
alltest

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,NaN
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,NaN
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,NaN
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,NaN
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [51]:
alldata=alltrain.append(alltest)
alldata

C:\Users\TEMP\ipykernel_17040\1029465771.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  alldata=alltrain.append(alltest)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [52]:
onehot2str={}
str_cols=[]
for c in alldata.columns:
    if str(alldata[c].dtype)=='object':
        str_cols.append(c)
        mapper={}
        idx=1
        for tag in alldata[c].unique():
            mapper[idx]=tag
            alldata.loc[alldata[c].values==tag,c]=idx
            idx+=1
            
        onehot2str[c]=mapper
print(str_cols)

['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

In [53]:
onehot2str

{'MSZoning': {1: 'RL', 2: 'RM', 3: 'C (all)', 4: 'FV', 5: 'RH', 6: nan},
 'Street': {1: 'Pave', 2: 'Grvl'},
 'Alley': {1: nan, 2: 'Grvl', 3: 'Pave'},
 'LotShape': {1: 'Reg', 2: 'IR1', 3: 'IR2', 4: 'IR3'},
 'LandContour': {1: 'Lvl', 2: 'Bnk', 3: 'Low', 4: 'HLS'},
 'Utilities': {1: 'AllPub', 2: 'NoSeWa', 3: nan},
 'LotConfig': {1: 'Inside', 2: 'FR2', 3: 'Corner', 4: 'CulDSac', 5: 'FR3'},
 'LandSlope': {1: 'Gtl', 2: 'Mod', 3: 'Sev'},
 'Neighborhood': {1: 'CollgCr',
  2: 'Veenker',
  3: 'Crawfor',
  4: 'NoRidge',
  5: 'Mitchel',
  6: 'Somerst',
  7: 'NWAmes',
  8: 'OldTown',
  9: 'BrkSide',
  10: 'Sawyer',
  11: 'NridgHt',
  12: 'NAmes',
  13: 'SawyerW',
  14: 'IDOTRR',
  15: 'MeadowV',
  16: 'Edwards',
  17: 'Timber',
  18: 'Gilbert',
  19: 'StoneBr',
  20: 'ClearCr',
  21: 'NPkVill',
  22: 'Blmngtn',
  23: 'BrDale',
  24: 'SWISU',
  25: 'Blueste'},
 'Condition1': {1: 'Norm',
  2: 'Feedr',
  3: 'PosN',
  4: 'Artery',
  5: 'RRAe',
  6: 'RRNn',
  7: 'RRAn',
  8: 'PosA',
  9: 'RRNe'},
 'Condition2': {1: 'Norm',
  2: 'Artery',
  3: 'RRNn',
  4: 'Feedr',
  5: 'PosN',
  6: 'PosA',
  7: 'RRAn',
  8: 'RRAe'},
 'BldgType': {1: '1Fam', 2: '2fmCon', 3: 'Duplex', 4: 'TwnhsE', 5: 'Twnhs'},
 'HouseStyle': {1: '2Story',
  2: '1Story',
  3: '1.5Fin',
  4: '1.5Unf',
  5: 'SFoyer',
  6: 'SLvl',
  7: '2.5Unf',
  8: '2.5Fin'},
 'RoofStyle': {1: 'Gable',
  2: 'Hip',
  3: 'Gambrel',
  4: 'Mansard',
  5: 'Flat',
  6: 'Shed'},
 'RoofMatl': {1: 'CompShg',
  2: 'WdShngl',
  3: 'Metal',
  4: 'WdShake',
  5: 'Membran',
  6: 'Tar&Grv',
  7: 'Roll',
  8: 'ClyTile'},
 'Exterior1st': {1: 'VinylSd',
  2: 'MetalSd',
  3: 'Wd Sdng',
  4: 'HdBoard',
  5: 'BrkFace',
  6: 'WdShing',
  7: 'CemntBd',
  8: 'Plywood',
  9: 'AsbShng',
  10: 'Stucco',
  11: 'BrkComm',
  12: 'AsphShn',
  13: 'Stone',
  14: 'ImStucc',
  15: 'CBlock',
  16: nan},
 'Exterior2nd': {1: 'VinylSd',
  2: 'MetalSd',
  3: 'Wd Shng',
  4: 'HdBoard',
  5: 'Plywood',
  6: 'Wd Sdng',
  7: 'CmentBd',
  8: 'BrkFace',
  9: 'Stucco',
  10: 'AsbShng',
  11: 'Brk Cmn',
  12: 'ImStucc',
  13: 'AsphShn',
  14: 'Stone',
  15: 'Other',
  16: 'CBlock',
  17: nan},
 'MasVnrType': {1: 'BrkFace', 2: 'None', 3: 'Stone', 4: 'BrkCmn', 5: nan},
 'ExterQual': {1: 'Gd', 2: 'TA', 3: 'Ex', 4: 'Fa'},
 'ExterCond': {1: 'TA', 2: 'Gd', 3: 'Fa', 4: 'Po', 5: 'Ex'},
 'Foundation': {1: 'PConc',
  2: 'CBlock',
  3: 'BrkTil',
  4: 'Wood',
  5: 'Slab',
  6: 'Stone'},
 'BsmtQual': {1: 'Gd', 2: 'TA', 3: 'Ex', 4: nan, 5: 'Fa'},
 'BsmtCond': {1: 'TA', 2: 'Gd', 3: nan, 4: 'Fa', 5: 'Po'},
 'BsmtExposure': {1: 'No', 2: 'Gd', 3: 'Mn', 4: 'Av', 5: nan},
 'BsmtFinType1': {1: 'GLQ',
  2: 'ALQ',
  3: 'Unf',
  4: 'Rec',
  5: 'BLQ',
  6: nan,
  7: 'LwQ'},
 'BsmtFinType2': {1: 'Unf',
  2: 'BLQ',
  3: nan,
  4: 'ALQ',
  5: 'Rec',
  6: 'LwQ',
  7: 'GLQ'},
 'Heating': {1: 'GasA',
  2: 'GasW',
  3: 'Grav',
  4: 'Wall',
  5: 'OthW',
  6: 'Floor'},
 'HeatingQC': {1: 'Ex', 2: 'Gd', 3: 'TA', 4: 'Fa', 5: 'Po'},
 'CentralAir': {1: 'Y', 2: 'N'},
 'Electrical': {1: 'SBrkr',
  2: 'FuseF',
  3: 'FuseA',
  4: 'FuseP',
  5: 'Mix',
  6: nan},
 'KitchenQual': {1: 'Gd', 2: 'TA', 3: 'Ex', 4: 'Fa', 5: nan},
 'Functional': {1: 'Typ',
  2: 'Min1',
  3: 'Maj1',
  4: 'Min2',
  5: 'Mod',
  6: 'Maj2',
  7: 'Sev',
  8: nan},
 'FireplaceQu': {1: nan, 2: 'TA', 3: 'Gd', 4: 'Fa', 5: 'Ex', 6: 'Po'},
 'GarageType': {1: 'Attchd',
  2: 'Detchd',
  3: 'BuiltIn',
  4: 'CarPort',
  5: nan,
  6: 'Basment',
  7: '2Types'},
 'GarageFinish': {1: 'RFn', 2: 'Unf', 3: 'Fin', 4: nan},
 'GarageQual': {1: 'TA', 2: 'Fa', 3: 'Gd', 4: nan, 5: 'Ex', 6: 'Po'},
 'GarageCond': {1: 'TA', 2: 'Fa', 3: nan, 4: 'Gd', 5: 'Po', 6: 'Ex'},
 'PavedDrive': {1: 'Y', 2: 'N', 3: 'P'},
 'PoolQC': {1: nan, 2: 'Ex', 3: 'Fa', 4: 'Gd'},
 'Fence': {1: nan, 2: 'MnPrv', 3: 'GdWo', 4: 'GdPrv', 5: 'MnWw'},
 'MiscFeature': {1: nan, 2: 'Shed', 3: 'Gar2', 4: 'Othr', 5: 'TenC'},
 'SaleType': {1: 'WD',
  2: 'New',
  3: 'COD',
  4: 'ConLD',
  5: 'ConLI',
  6: 'CWD',
  7: 'ConLw',
  8: 'Con',
  9: 'Oth',
  10: nan},
 'SaleCondition': {1: 'Normal',
  2: 'Abnorml',
  3: 'Partial',
  4: 'AdjLand',
  5: 'Alloca',
  6: 'Family'}}

In [54]:
alldata

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,1,65.0,8450,1,NaN,1,1,1,1,...,0,NaN,NaN,NaN,0,2,2008,1,1,208500.0
2,20,1,80.0,9600,1,NaN,1,1,1,2,...,0,NaN,NaN,NaN,0,5,2007,1,1,181500.0
3,60,1,68.0,11250,1,NaN,2,1,1,1,...,0,NaN,NaN,NaN,0,9,2008,1,1,223500.0
4,70,1,60.0,9550,1,NaN,2,1,1,3,...,0,NaN,NaN,NaN,0,2,2006,1,2,140000.0
5,60,1,84.0,14260,1,NaN,2,1,1,2,...,0,NaN,NaN,NaN,0,12,2008,1,1,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,2,21.0,1936,1,NaN,1,1,1,1,...,0,NaN,NaN,NaN,0,6,2006,1,1,NaN
2916,160,2,21.0,1894,1,NaN,1,1,1,1,...,0,NaN,NaN,NaN,0,4,2006,1,2,NaN
2917,20,1,160.0,20000,1,NaN,1,1,1,1,...,0,NaN,NaN,NaN,0,9,2006,1,2,NaN
2918,85,1,62.0,10441,1,NaN,1,1,1,1,...,0,NaN,2,2,700,7,2006,1,1,NaN
2919,60,1,74.0,9627,1,NaN,1,1,1,1,...,0,NaN,NaN,NaN,0,11,2006,1,1,NaN

# fill in missing values

## KNN

In [16]:
from sklearn import neighbors

In [55]:
tempdata=alldata.loc[:,~alldata.isnull().any().values]
n_neighbors=10
# 如果包含空值的列是object列，那么是离散的，应该用聚类，否则回归
for col in alldata.columns[alldata.isnull().any().values]:
    if col=="SalePrice":
        continue
    # 按照行切分，提取非nan的行用于训练
    notnan=alldata.loc[:,col].notna()
    isnan=alldata.loc[:,col].isna()
    if col in str_cols:
        # 聚类
        clf = neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
        clf.fit(tempdata.loc[notnan], alldata.loc[notnan,col].astype(int))
        alldata.loc[isnan,col]=clf.predict(tempdata.loc[isnan])
    else:
        # 回归
        rgs = neighbors.KNeighborsRegressor(n_neighbors, weights='distance')
        rgs.fit(tempdata.loc[notnan], alldata.loc[notnan,col].astype(int))
        alldata.loc[isnan,col]=rgs.predict(tempdata.loc[isnan])

In [56]:
tempdata

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,8450,1,1,1,1,1,1,1,1,...,0,61,0,0,0,0,0,2,2008,1
2,20,9600,1,1,1,2,1,2,2,1,...,298,0,0,0,0,0,0,5,2007,1
3,60,11250,1,2,1,1,1,1,1,1,...,0,42,0,0,0,0,0,9,2008,1
4,70,9550,1,2,1,3,1,3,1,1,...,0,35,272,0,0,0,0,2,2006,2
5,60,14260,1,2,1,2,1,4,1,1,...,192,84,0,0,0,0,0,12,2008,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,1936,1,1,1,1,1,15,1,1,...,0,0,0,0,0,0,0,6,2006,1
2916,160,1894,1,1,1,1,1,15,1,1,...,0,24,0,0,0,0,0,4,2006,2
2917,20,20000,1,1,1,1,1,5,1,1,...,474,0,0,0,0,0,0,9,2006,2
2918,85,10441,1,1,1,1,1,5,1,1,...,80,32,0,0,0,0,700,7,2006,1
2919,60,9627,1,1,1,1,2,5,1,1,...,190,48,0,0,0,0,0,11,2006,1

In [60]:
print(alldata.isna().any())
alldata.isna().any().value_counts()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice         True
Length: 80, dtype: bool

False    79
True      1
dtype: int64

# split train and valid

In [63]:
test=alldata.loc[alldata.loc[:,"SalePrice"].isna()]
train1=alldata.loc[~alldata.loc[:,"SalePrice"].isna()]

In [66]:
sorted_train=train1.sort_values(["YrSold","MoSold"])
sorted_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
142,20,1,78.000000,11645,1,2,1,1,1,1,...,0,2,2,2,0,1,2006,1,1,260000.0
170,20,1,105.281444,16669,1,2,2,1,1,3,...,0,2,2,2,0,1,2006,1,1,228000.0
303,20,1,118.000000,13704,1,2,2,1,1,3,...,0,2,2,2,0,1,2006,1,1,205000.0
371,60,1,62.769858,8121,1,2,2,1,1,1,...,0,4,2,2,0,1,2006,1,1,172400.0
412,190,1,100.000000,34650,1,2,1,2,1,1,...,0,2,4,2,0,1,2006,1,1,145000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,20,1,65.000000,8450,1,2,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,142000.0
706,190,2,70.000000,5600,1,2,1,1,1,1,...,0,4,2,4,3500,7,2010,1,1,55000.0
1145,190,1,60.000000,12180,1,2,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,80000.0
1161,160,1,24.000000,2280,1,3,1,1,1,1,...,0,4,4,2,0,7,2010,1,1,146000.0
1422,120,1,53.000000,4043,1,3,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,127500.0

In [67]:
valid=sorted_train.groupby(["YrSold","MoSold"]).sample(frac=0.1, random_state=2)
valid

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
412,190,1,100.000000,34650,1,2,1,2,1,1,...,0,2,4,2,0,1,2006,1,1,145000.0
546,50,1,94.184568,13837,1,2,2,1,1,3,...,0,2,4,2,0,2,2006,1,1,229000.0
1247,60,4,65.000000,8125,1,2,1,1,1,1,...,0,4,2,2,0,3,2006,2,3,186500.0
512,120,1,40.000000,6792,1,3,2,1,1,1,...,0,4,3,2,0,3,2006,2,3,202665.0
86,60,1,121.000000,16059,1,2,1,1,1,3,...,0,2,2,2,0,4,2006,1,1,260000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,120,1,60.536678,6820,1,3,2,1,1,3,...,0,4,2,2,0,6,2010,1,1,212000.0
143,50,1,71.000000,8520,1,2,1,1,1,3,...,0,4,2,2,0,6,2010,1,1,166000.0
1381,30,1,45.000000,8212,1,2,1,1,1,1,...,0,4,3,2,0,6,2010,1,1,58500.0
69,30,2,47.000000,4608,1,2,1,1,1,3,...,0,4,2,2,0,6,2010,1,1,80000.0
706,190,2,70.000000,5600,1,2,1,1,1,1,...,0,4,2,4,3500,7,2010,1,1,55000.0

In [68]:
valid.groupby(["YrSold","MoSold"]).count()

               MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
YrSold MoSold
2006   1                1         1            1        1       1      1
       2                1         1            1        1       1      1
       3                2         2            2        2       2      2
       4                3         3            3        3       3      3
       5                4         4            4        4       4      4
       6                5         5            5        5       5      5
       7                7         7            7        7       7      7
       8                2         2            2        2       2      2
       9                2         2            2        2       2      2
       10               2         2            2        2       2      2
       11               2         2            2        2       2      2
       12               1         1            1        1       1      1
2007   1                1         1            1        1       1      1
       2                1         1            1        1       1      1
       3                2         2            2        2       2      2
       4                2         2            2        2       2      2
       5                4         4            4        4       4      4
       6                6         6            6        6       6      6
       7                5         5            5        5       5      5
       8                4         4            4        4       4      4
       9                1         1            1        1       1      1
       10               2         2            2        2       2      2
       11               2         2            2        2       2      2
       12               2         2            2        2       2      2
2008   1                1         1            1        1       1      1
       2                1         1            1        1       1      1
       3                2         2            2        2       2      2
       4                3         3            3        3       3      3
       5                4         4            4        4       4      4
       6                5         5            5        5       5      5
       7                5         5            5        5       5      5
       8                3         3            3        3       3      3
       9                2         2            2        2       2      2
       10               2         2            2        2       2      2
       11               2         2            2        2       2      2
       12               1         1            1        1       1      1
2009   1                1         1            1        1       1      1
       2                1         1            1        1       1      1
       3                2         2            2        2       2      2
       4                3         3            3        3       3      3
       5                4         4            4        4       4      4
       6                6         6            6        6       6      6
       7                6         6            6        6       6      6
       8                3         3            3        3       3      3
       9                2         2            2        2       2      2
       10               3         3            3        3       3      3
       11               2         2            2        2       2      2
       12               2         2            2        2       2      2
2010   1                1         1            1        1       1      1
       2                2         2            2        2       2      2
       3                2         2            2        2       2      2
       4                4         4            4        4       4      4
       5                5         5            5        5       5      5
       6                4         4            4        4       4      4
       7                1         1            1        1       1      1

               LotShape  LandContour  Utilities  LotConfig  ...  3SsnPorch  \
YrSold MoSold                                               ...
2006   1              1            1          1          1  ...          1
       2              1            1          1          1  ...          1
       3              2            2          2          2  ...          2
       4              3            3          3          3  ...          3
       5              4            4          4          4  ...          4
       6              5            5          5          5  ...          5
       7              7            7          7          7  ...          7
       8              2            2          2          2  ...          2
       9              2            2          2          2  ...          2
       10             2            2          2          2  ...          2
       11             2            2          2          2  ...          2
       12             1            1          1          1  ...          1
2007   1              1            1          1          1  ...          1
       2              1            1          1          1  ...          1
       3              2            2          2          2  ...          2
       4              2            2          2          2  ...          2
       5              4            4          4          4  ...          4
       6              6            6          6          6  ...          6
       7              5            5          5          5  ...          5
       8              4            4          4          4  ...          4
       9              1            1          1          1  ...          1
       10             2            2          2          2  ...          2
       11             2            2          2          2  ...          2
       12             2            2          2          2  ...          2
2008   1              1            1          1          1  ...          1
       2              1            1          1          1  ...          1
       3              2            2          2          2  ...          2
       4              3            3          3          3  ...          3
       5              4            4          4          4  ...          4
       6              5            5          5          5  ...          5
       7              5            5          5          5  ...          5
       8              3            3          3          3  ...          3
       9              2            2          2          2  ...          2
       10             2            2          2          2  ...          2
       11             2            2          2          2  ...          2
       12             1            1          1          1  ...          1
2009   1              1            1          1          1  ...          1
       2              1            1          1          1  ...          1
       3              2            2          2          2  ...          2
       4              3            3          3          3  ...          3
       5              4            4          4          4  ...          4
       6              6            6          6          6  ...          6
       7              6            6          6          6  ...          6
       8              3            3          3          3  ...          3
       9              2            2          2          2  ...          2
       10             3            3          3          3  ...          3
       11             2            2          2          2  ...          2
       12             2            2          2          2  ...          2
2010   1              1            1          1          1  ...          1
       2              2            2          2          2  ...          2
       3              2            2          2          2  ...          2
       4              4            4          4          4  ...          4
       5              5            5          5          5  ...          5
       6              4            4          4          4  ...          4
       7              1            1          1          1  ...          1

               ScreenPorch  PoolArea  PoolQC  Fence  MiscFeature  MiscVal  \
YrSold MoSold
2006   1                 1         1       1      1            1        1
       2                 1         1       1      1            1        1
       3                 2         2       2      2            2        2
       4                 3         3       3      3            3        3
       5                 4         4       4      4            4        4
       6                 5         5       5      5            5        5
       7                 7         7       7      7            7        7
       8                 2         2       2      2            2        2
       9                 2         2       2      2            2        2
       10                2         2       2      2            2        2
       11                2         2       2      2            2        2
       12                1         1       1      1            1        1
2007   1                 1         1       1      1            1        1
       2                 1         1       1      1            1        1
       3                 2         2       2      2            2        2
       4                 2         2       2      2            2        2
       5                 4         4       4      4            4        4
       6                 6         6       6      6            6        6
       7                 5         5       5      5            5        5
       8                 4         4       4      4            4        4
       9                 1         1       1      1            1        1
       10                2         2       2      2            2        2
       11                2         2       2      2            2        2
       12                2         2       2      2            2        2
2008   1                 1         1       1      1            1        1
       2                 1         1       1      1            1        1
       3                 2         2       2      2            2        2
       4                 3         3       3      3            3        3
       5                 4         4       4      4            4        4
       6                 5         5       5      5            5        5
       7                 5         5       5      5            5        5
       8                 3         3       3      3            3        3
       9                 2         2       2      2            2        2
       10                2         2       2      2            2        2
       11                2         2       2      2            2        2
       12                1         1       1      1            1        1
2009   1                 1         1       1      1            1        1
       2                 1         1       1      1            1        1
       3                 2         2       2      2            2        2
       4                 3         3       3      3            3        3
       5                 4         4       4      4            4        4
       6                 6         6       6      6            6        6
       7                 6         6       6      6            6        6
       8                 3         3       3      3            3        3
       9                 2         2       2      2            2        2
       10                3         3       3      3            3        3
       11                2         2       2      2            2        2
       12                2         2       2      2            2        2
2010   1                 1         1       1      1            1        1
       2                 2         2       2      2            2        2
       3                 2         2       2      2            2        2
       4                 4         4       4      4            4        4
       5                 5         5       5      5            5        5
       6                 4         4       4      4            4        4
       7                 1         1       1      1            1        1

               SaleType  SaleCondition  SalePrice
YrSold MoSold
2006   1              1              1          1
       2              1              1          1
       3              2              2          2
       4              3              3          3
       5              4              4          4
       6              5              5          5
       7              7              7          7
       8              2              2          2
       9              2              2          2
       10             2              2          2
       11             2              2          2
       12             1              1          1
2007   1              1              1          1
       2              1              1          1
       3              2              2          2
       4              2              2          2
       5              4              4          4
       6              6              6          6
       7              5              5          5
       8              4              4          4
       9              1              1          1
       10             2              2          2
       11             2              2          2
       12             2              2          2
2008   1              1              1          1
       2              1              1          1
       3              2              2          2
       4              3              3          3
       5              4              4          4
       6              5              5          5
       7              5              5          5
       8              3              3          3
       9              2              2          2
       10             2              2          2
       11             2              2          2
       12             1              1          1
2009   1              1              1          1
       2              1              1          1
       3              2              2          2
       4              3              3          3
       5              4              4          4
       6              6              6          6
       7              6              6          6
       8              3              3          3
       9              2              2          2
       10             3              3          3
       11             2              2          2
       12             2              2          2
2010   1              1              1          1
       2              2              2          2
       3              2              2          2
       4              4              4          4
       5              5              5          5
       6              4              4          4
       7              1              1          1

[55 rows x 78 columns]

In [32]:
sorted_train.groupby(["YrSold","MoSold"]).count()

               MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
YrSold MoSold
2006   1               10        10            7       10      10      1
       2                9         9            7        9       9      0
       3               25        25           22       25      25      1
       4               27        27           23       27      27      6
       5               38        38           31       38      38      2
       6               48        48           40       48      48      3
       7               67        67           59       67      67      2
       8               23        23           20       23      23      2
       9               15        15           15       15      15      1
       10              24        24           22       24      24      1
       11              16        16           11       16      16      0
       12              12        12            8       12      12      0
2007   1               13        13           12       13      13      0
       2                8         8            7        8       8      0
       3               23        23           15       23      23      1
       4               23        23           20       23      23      1
       5               43        43           34       43      43      1
       6               59        59           43       59      59      5
       7               51        51           43       51      51      3
       8               40        40           32       40      40      4
       9               11        11           10       11      11      1
       10              16        16           12       16      16      1
       11              24        24           21       24      24      2
       12              18        18           17       18      18      0
2008   1               13        13           12       13      13      0
       2               10        10           10       10      10      1
       3               18        18           13       18      18      4
       4               26        26           22       26      26      4
       5               38        38           29       38      38      1
       6               51        51           41       51      51      9
       7               49        49           39       49      49      3
       8               29        29           27       29      29      2
       9               17        17           14       17      17      1
       10              22        22           19       22      22      0
       11              17        17           15       17      17      1
       12              14        14           13       14      14      1
2009   1               12        12            9       12      12      1
       2               10        10            8       10      10      1
       3               19        19           15       19      19      1
       4               26        26           22       26      26      1
       5               37        37           30       37      37      2
       6               59        59           45       59      59      3
       7               61        61           54       61      61      4
       8               30        30           24       30      30      3
       9               20        20           18       20      20      1
       10              27        27           23       27      27      1
       11              22        22           16       22      22      1
       12              15        15            9       15      15      1
2010   1               10        10            9       10      10      1
       2               15        15           12       15      15      0
       3               21        21           17       21      21      1
       4               39        39           32       39      39      0
       5               48        48           38       48      48      1
       6               36        36           30       36      36      3
       7                6         6            5        6       6      0

               LotShape  LandContour  Utilities  LotConfig  ...  3SsnPorch  \
YrSold MoSold                                               ...
2006   1             10           10         10         10  ...         10
       2              9            9          9          9  ...          9
       3             25           25         25         25  ...         25
       4             27           27         27         27  ...         27
       5             38           38         38         38  ...         38
       6             48           48         48         48  ...         48
       7             67           67         67         67  ...         67
       8             23           23         23         23  ...         23
       9             15           15         15         15  ...         15
       10            24           24         24         24  ...         24
       11            16           16         16         16  ...         16
       12            12           12         12         12  ...         12
2007   1             13           13         13         13  ...         13
       2              8            8          8          8  ...          8
       3             23           23         23         23  ...         23
       4             23           23         23         23  ...         23
       5             43           43         43         43  ...         43
       6             59           59         59         59  ...         59
       7             51           51         51         51  ...         51
       8             40           40         40         40  ...         40
       9             11           11         11         11  ...         11
       10            16           16         16         16  ...         16
       11            24           24         24         24  ...         24
       12            18           18         18         18  ...         18
2008   1             13           13         13         13  ...         13
       2             10           10         10         10  ...         10
       3             18           18         18         18  ...         18
       4             26           26         26         26  ...         26
       5             38           38         38         38  ...         38
       6             51           51         51         51  ...         51
       7             49           49         49         49  ...         49
       8             29           29         29         29  ...         29
       9             17           17         17         17  ...         17
       10            22           22         22         22  ...         22
       11            17           17         17         17  ...         17
       12            14           14         14         14  ...         14
2009   1             12           12         12         12  ...         12
       2             10           10         10         10  ...         10
       3             19           19         19         19  ...         19
       4             26           26         26         26  ...         26
       5             37           37         37         37  ...         37
       6             59           59         59         59  ...         59
       7             61           61         61         61  ...         61
       8             30           30         30         30  ...         30
       9             20           20         20         20  ...         20
       10            27           27         27         27  ...         27
       11            22           22         22         22  ...         22
       12            15           15         15         15  ...         15
2010   1             10           10         10         10  ...         10
       2             15           15         15         15  ...         15
       3             21           21         21         21  ...         21
       4             39           39         39         39  ...         39
       5             48           48         48         48  ...         48
       6             36           36         36         36  ...         36
       7              6            6          6          6  ...          6

               ScreenPorch  PoolArea  PoolQC  Fence  MiscFeature  MiscVal  \
YrSold MoSold
2006   1                10        10       1      3            0       10
       2                 9         9       0      2            0        9
       3                25        25       1      4            1       25
       4                27        27       0      2            1       27
       5                38        38       0      5            1       38
       6                48        48       0     10            0       48
       7                67        67       1     12            3       67
       8                23        23       1      4            0       23
       9                15        15       0      2            1       15
       10               24        24       0      2            1       24
       11               16        16       0      3            0       16
       12               12        12       0      3            0       12
2007   1                13        13       0      4            0       13
       2                 8         8       0      1            0        8
       3                23        23       0      4            0       23
       4                23        23       0      6            3       23
       5                43        43       0      7            1       43
       6                59        59       0     16            2       59
       7                51        51       1     11            3       51
       8                40        40       0      6            3       40
       9                11        11       0      1            0       11
       10               16        16       0      2            0       16
       11               24        24       0      2            0       24
       12               18        18       0      4            0       18
2008   1                13        13       1      3            0       13
       2                10        10       0      2            0       10
       3                18        18       0      1            0       18
       4                26        26       0      6            0       26
       5                38        38       0     11            1       38
       6                51        51       0     10            1       51
       7                49        49       1      6            1       49
       8                29        29       0      3            3       29
       9                17        17       0      4            1       17
       10               22        22       0      7            1       22
       11               17        17       0      2            1       17
       12               14        14       0      3            0       14
2009   1                12        12       0      0            0       12
       2                10        10       0      1            0       10
       3                19        19       0      4            1       19
       4                26        26       0      5            1       26
       5                37        37       0      7            1       37
       6                59        59       0      7            1       59
       7                61        61       0     11            0       61
       8                30        30       0      9            1       30
       9                20        20       0      2            1       20
       10               27        27       0      8            2       27
       11               22        22       0     10            3       22
       12               15        15       0      3            0       15
2010   1                10        10       0      2            1       10
       2                15        15       0      6            0       15
       3                21        21       0      5            3       21
       4                39        39       0      6            0       39
       5                48        48       0     14            5       48
       6                36        36       0      6            4       36
       7                 6         6       0      1            1        6

               SaleType  SaleCondition  SalePrice
YrSold MoSold
2006   1             10             10         10
       2              9              9          9
       3             25             25         25
       4             27             27         27
       5             38             38         38
       6             48             48         48
       7             67             67         67
       8             23             23         23
       9             15             15         15
       10            24             24         24
       11            16             16         16
       12            12             12         12
2007   1             13             13         13
       2              8              8          8
       3             23             23         23
       4             23             23         23
       5             43             43         43
       6             59             59         59
       7             51             51         51
       8             40             40         40
       9             11             11         11
       10            16             16         16
       11            24             24         24
       12            18             18         18
2008   1             13             13         13
       2             10             10         10
       3             18             18         18
       4             26             26         26
       5             38             38         38
       6             51             51         51
       7             49             49         49
       8             29             29         29
       9             17             17         17
       10            22             22         22
       11            17             17         17
       12            14             14         14
2009   1             12             12         12
       2             10             10         10
       3             19             19         19
       4             26             26         26
       5             37             37         37
       6             59             59         59
       7             61             61         61
       8             30             30         30
       9             20             20         20
       10            27             27         27
       11            22             22         22
       12            15             15         15
2010   1             10             10         10
       2             15             15         15
       3             21             21         21
       4             39             39         39
       5             48             48         48
       6             36             36         36
       7              6              6          6

[55 rows x 78 columns]

In [69]:
train_idx=list(set(list(sorted_train.index)).difference(set(list(valid.index))))
len(train_idx)

1311

In [71]:
train=sorted_train.loc[train_idx].sort_values(by=["YrSold","MoSold"])
train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
142,20,1,78.000000,11645,1,2,1,1,1,1,...,0,2,2,2,0,1,2006,1,1,260000.0
170,20,1,105.281444,16669,1,2,2,1,1,3,...,0,2,2,2,0,1,2006,1,1,228000.0
303,20,1,118.000000,13704,1,2,2,1,1,3,...,0,2,2,2,0,1,2006,1,1,205000.0
371,60,1,62.769858,8121,1,2,2,1,1,1,...,0,4,2,2,0,1,2006,1,1,172400.0
665,20,1,49.000000,20896,1,2,3,1,1,4,...,0,4,2,2,0,1,2006,2,3,423000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,20,1,115.794832,19900,1,2,1,1,1,1,...,0,4,4,2,0,7,2010,1,1,180000.0
420,20,1,65.000000,8450,1,2,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,142000.0
1145,190,1,60.000000,12180,1,2,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,80000.0
1161,160,1,24.000000,2280,1,3,1,1,1,1,...,0,4,4,2,0,7,2010,1,1,146000.0
1422,120,1,53.000000,4043,1,3,1,1,1,1,...,0,4,2,2,0,7,2010,1,1,127500.0

In [72]:
set(list(train.index)).intersection(set(list(valid.index)))

set()

# save train

In [73]:
sorted_train.groupby(["YrSold","MoSold"]).mean().to_csv("mean_data.csv")

In [74]:
train.to_csv("preprocessed_train.csv")
valid.to_csv("preprocessed_valid.csv")
test.to_csv("preprocessed_test.csv")

In [76]:
import json
with open("onehot2str.json","w") as f:
    json.dump(onehot2str,f)

In [78]:
with open("onehot2str.json","r") as f:
    print(json.load(f))

{'MSZoning': {'1': 'RL', '2': 'RM', '3': 'C (all)', '4': 'FV', '5': 'RH', '6': nan}, 'Street': {'1': 'Pave', '2': 'Grvl'}, 'Alley': {'1': nan, '2': 'Grvl', '3': 'Pave'}, 'LotShape': {'1': 'Reg', '2': 'IR1', '3': 'IR2', '4': 'IR3'}, 'LandContour': {'1': 'Lvl', '2': 'Bnk', '3': 'Low', '4': 'HLS'}, 'Utilities': {'1': 'AllPub', '2': 'NoSeWa', '3': nan}, 'LotConfig': {'1': 'Inside', '2': 'FR2', '3': 'Corner', '4': 'CulDSac', '5': 'FR3'}, 'LandSlope': {'1': 'Gtl', '2': 'Mod', '3': 'Sev'}, 'Neighborhood': {'1': 'CollgCr', '2': 'Veenker', '3': 'Crawfor', '4': 'NoRidge', '5': 'Mitchel', '6': 'Somerst', '7': 'NWAmes', '8': 'OldTown', '9': 'BrkSide', '10': 'Sawyer', '11': 'NridgHt', '12': 'NAmes', '13': 'SawyerW', '14': 'IDOTRR', '15': 'MeadowV', '16': 'Edwards', '17': 'Timber', '18': 'Gilbert', '19': 'StoneBr', '20': 'ClearCr', '21': 'NPkVill', '22': 'Blmngtn', '23': 'BrDale', '24': 'SWISU', '25': 'Blueste'}, 'Condition1': {'1': 'Norm', '2': 'Feedr', '3': 'PosN', '4': 'Artery', '5': 'RRAe', '6': 'RRNn', '7': 'RRAn', '8': 'PosA', '9': 'RRNe'}, 'Condition2': {'1': 'Norm', '2': 'Artery', '3': 'RRNn', '4': 'Feedr', '5': 'PosN', '6': 'PosA', '7': 'RRAn', '8': 'RRAe'}, 'BldgType': {'1': '1Fam', '2': '2fmCon', '3': 'Duplex', '4': 'TwnhsE', '5': 'Twnhs'}, 'HouseStyle': {'1': '2Story', '2': '1Story', '3': '1.5Fin', '4': '1.5Unf', '5': 'SFoyer', '6': 'SLvl', '7': '2.5Unf', '8': '2.5Fin'}, 'RoofStyle': {'1': 'Gable', '2': 'Hip', '3': 'Gambrel', '4': 'Mansard', '5': 'Flat', '6': 'Shed'}, 'RoofMatl': {'1': 'CompShg', '2': 'WdShngl', '3': 'Metal', '4': 'WdShake', '5': 'Membran', '6': 'Tar&Grv', '7': 'Roll', '8': 'ClyTile'}, 'Exterior1st': {'1': 'VinylSd', '2': 'MetalSd', '3': 'Wd Sdng', '4': 'HdBoard', '5': 'BrkFace', '6': 'WdShing', '7': 'CemntBd', '8': 'Plywood', '9': 'AsbShng', '10': 'Stucco', '11': 'BrkComm', '12': 'AsphShn', '13': 'Stone', '14': 'ImStucc', '15': 'CBlock', '16': nan}, 'Exterior2nd': {'1': 'VinylSd', '2': 'MetalSd', '3': 'Wd Shng', '4': 'HdBoard', '5': 'Plywood', '6': 'Wd Sdng', '7': 'CmentBd', '8': 'BrkFace', '9': 'Stucco', '10': 'AsbShng', '11': 'Brk Cmn', '12': 'ImStucc', '13': 'AsphShn', '14': 'Stone', '15': 'Other', '16': 'CBlock', '17': nan}, 'MasVnrType': {'1': 'BrkFace', '2': 'None', '3': 'Stone', '4': 'BrkCmn', '5': nan}, 'ExterQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': 'Fa'}, 'ExterCond': {'1': 'TA', '2': 'Gd', '3': 'Fa', '4': 'Po', '5': 'Ex'}, 'Foundation': {'1': 'PConc', '2': 'CBlock', '3': 'BrkTil', '4': 'Wood', '5': 'Slab', '6': 'Stone'}, 'BsmtQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': nan, '5': 'Fa'}, 'BsmtCond': {'1': 'TA', '2': 'Gd', '3': nan, '4': 'Fa', '5': 'Po'}, 'BsmtExposure': {'1': 'No', '2': 'Gd', '3': 'Mn', '4': 'Av', '5': nan}, 'BsmtFinType1': {'1': 'GLQ', '2': 'ALQ', '3': 'Unf', '4': 'Rec', '5': 'BLQ', '6': nan, '7': 'LwQ'}, 'BsmtFinType2': {'1': 'Unf', '2': 'BLQ', '3': nan, '4': 'ALQ', '5': 'Rec', '6': 'LwQ', '7': 'GLQ'}, 'Heating': {'1': 'GasA', '2': 'GasW', '3': 'Grav', '4': 'Wall', '5': 'OthW', '6': 'Floor'}, 'HeatingQC': {'1': 'Ex', '2': 'Gd', '3': 'TA', '4': 'Fa', '5': 'Po'}, 'CentralAir': {'1': 'Y', '2': 'N'}, 'Electrical': {'1': 'SBrkr', '2': 'FuseF', '3': 'FuseA', '4': 'FuseP', '5': 'Mix', '6': nan}, 'KitchenQual': {'1': 'Gd', '2': 'TA', '3': 'Ex', '4': 'Fa', '5': nan}, 'Functional': {'1': 'Typ', '2': 'Min1', '3': 'Maj1', '4': 'Min2', '5': 'Mod', '6': 'Maj2', '7': 'Sev', '8': nan}, 'FireplaceQu': {'1': nan, '2': 'TA', '3': 'Gd', '4': 'Fa', '5': 'Ex', '6': 'Po'}, 'GarageType': {'1': 'Attchd', '2': 'Detchd', '3': 'BuiltIn', '4': 'CarPort', '5': nan, '6': 'Basment', '7': '2Types'}, 'GarageFinish': {'1': 'RFn', '2': 'Unf', '3': 'Fin', '4': nan}, 'GarageQual': {'1': 'TA', '2': 'Fa', '3': 'Gd', '4': nan, '5': 'Ex', '6': 'Po'}, 'GarageCond': {'1': 'TA', '2': 'Fa', '3': nan, '4': 'Gd', '5': 'Po', '6': 'Ex'}, 'PavedDrive': {'1': 'Y', '2': 'N', '3': 'P'}, 'PoolQC': {'1': nan, '2': 'Ex', '3': 'Fa', '4': 'Gd'}, 'Fence': {'1': nan, '2': 'MnPrv', '3': 'GdWo', '4': 'GdPrv', '5': 'MnWw'}, 'MiscFeature': {'1': nan, '2': 'Shed', '3': 'Gar2', '4': 'Othr', '5': 'TenC'}, 'SaleType': {'1': 'WD', '2': 'New', '3': 'COD', '4': 'ConLD', '5': 'ConLI', '6': 'CWD', '7': 'ConLw', '8': 'Con', '9': 'Oth', '10': nan}, 'SaleCondition': {'1': 'Normal', '2': 'Abnorml', '3': 'Partial', '4': 'AdjLand', '5': 'Alloca', '6': 'Family'}}